### ISSUE TITLE
Sorting Algorithm

### ISSUE THREAD

**Issue by raidenkhan** [raidenkhan/sortingVisualizer-PureHtmlCssJs#1]
Impelement sorting algorithm with javascript

**Comment by aryankshl** [comment]
hey @raidenkhan can you please assign this to me?

**Comment by Asharma538** [comment]
Hey @raidenkhan please assign this issue to me, also please elaborate on what kind of sorting algorithm is to be implemented.

**Comment by raidenkhan** [comment]
> hey @raidenkhan can you please assign this to me?

You are to implement each and every sorting algorithm in javascript. I mean one algorithm for radix sort, insertion sort , bubble sort and merge sort
